### ISSUE TITLE
Error: `DM create itematt` generates errors

### ISSUE THREAD

**Issue by adrienlaws** [Meridian59/Meridian59#1007]
## What

- Creating an item with `dm create itematt holy` generates 2 server errors
>  `[weapon.bof (679)] InterpretBinaryAssign can't and 2 vars 1,0 and 0,0`
>  `[weapon.bof (667)] InterpretBinaryAssign can't or 2 vars 1,0 and 0,0`
- Viewing the item after adding the attribute also generates a server error
>  `[waspellt.bof (122)] C_AppendTempString can't set from NIL`

### Notes
- occurs occurs with the available `spelltypes`
    - fire
    - cold
    - shock
    - holy
    - unholy
    - acid
- only seems to occur the first time you do it to a weapon as a dm
  - speculating the other attributes are not added in subsequent commands

### Example
https://github.com/user-attachments/assets/b5c80c07-be24-4bc8-b7d8-6818b0e19668

### Expected Result
- using `dm create itematt <spelltype>` should not generate any errors
- looking at an item created with `dm create item att <spelltype> should not generate errors

**Comment by davidklaw** [comment]
I've found that when these attributes are added through DM commands, they don't provide a `timer_duration` to `AddToItem`. When this reaches `SetTimer` in `ItemAttribute::AddToItem`, `SetTimer` returns `$` and saves it to the data object. This causes a chain reaction: when `WeapAttSpellType::AddEffects` runs later, it retrieves data from the wrong position.

I assume a timer duration isn't provided when created via admin command to make it indefinite. Is that what we want?

I can provide more detail if needed.
