### ISSUE TITLE
Typo in Lute Equip sound

### ISSUE THREAD

**Issue by M59Khan** [Meridian59/Meridian59#174]
I found a typo in lute.kod

kod/object/item/passitem/instrum/lute.kod

line 26:  lute_used_wav_rsc = lute_eqip.wav

It should say "lute_equip.wav" not "lute_eqip.wav" to match the sound in the resource folder

Shakrune and I were testing sounds and we found this typo.

Apologies if this report is not in the correct section/formatted properly.  It's my first one.

**Comment by Meridian59** [comment]
Fixed awhile ago.
