### ISSUE TITLE
Times roll over after 5 years or so

### ISSUE THREAD

**Issue by Meridian59** [Meridian59/Meridian59#22]
Because all numbers are stored in 28 bits in Blakod, every 5 years or so, absolute times stored in Blakod roll over, resulting in various breakages (monsters become unresponsive, etc.) that require manual intervention to fix.  Players get a message that "you have attacked someone too recently" that takes a few hours of time online to clear.

**Comment by dalu** [comment]
Where are they stored or rather defined?

**Comment by marcelkauf** [comment]
I guess this can be closed after the recent bugfix ?!
