### ISSUE TITLE
Missing soundfile flight.wav in light.kod

### ISSUE THREAD

**Issue by cyberjunk** [Meridian59/Meridian59#224]
There is a missing soundfile...
light.kod references a non existant flight.wav

At least I wasn't able to find it in my resources (?)

https://github.com/Meridian59/Meridian59/blob/master/kod/object/passive/spell/roomench/light.kod

See line 33:
light_sound = flight.wav

**Comment by Meridian59** [comment]
I don't have it either.  Does anyone have a copy?

**Comment by davidklaw** [comment]
I was able to install the Insurrection and Dark Auspices discs, but neither had this file present in their resources.
