### ISSUE TITLE
Ugliness in the display of player names

### ISSUE THREAD

**Issue by Meridian59** [Meridian59/Meridian59#24]
There are at least two problems with the display of player names in the 3D area when using the hardware renderer:
- There's z-flighting between the name and its black "shadow"
- Kerning isn't done quite right, and so there's sometimes a lot of extra space between letters.

**Comment by cyberjunk** [comment]
>> There's z-flighting between the name and its black "shadow"

Really? Different than on 103? I don't think we have z-fighting there for the names..
You could try increasing the delta between the following two values in D3DRenderNamesDraw3D (these are the zbias values for the name and the shadowname) - Like turn 254 into 250...

>> if (offset == 0)
pChunk->zBias = 255;
else
pChunk->zBias = 254;

It also should be mentioned that we use the following call also affecting DEPTHBIAS, in D3DRenderInit, which seems not yet be part of your port:

>> IDirect3DDevice9_SetRenderState(gpD3DDevice, D3DRS_SLOPESCALEDEPTHBIAS, F2DW(1.0f));

**Comment by Meridian59** [comment]
I think the z fighting is fixed thanks to the DX9 upgrade.  Kerning still
needs some work though.

**Comment by davidklaw** [comment]
@Meridian59 Is this the type of kerning issue you're referring to? Where the in-game font rendering looks like the Paint version and not Photoshop?

![image](https://user-images.githubusercontent.com/467443/180676475-14a5a3a4-646b-4c11-abd4-645a4c40ab2e.png)

**Comment by akirmse** [comment]
Yes.  It looks really bad on the lowercase "f", if I remember right.

**Comment by davidklaw** [comment]
![image](https://user-images.githubusercontent.com/467443/180693310-d58b6e46-5129-414e-9069-15b42deac57a.png)
