### ISSUE TITLE
Make the Inventory sortable

### ISSUE THREAD

**Issue by Serpentiel-zz** [Meridian59/Meridian59#262]
At the moment, to clean up your inventory you have to throw everything on the floor and take it in the right order.
It would be awesome if you could clean up your inventory by moving items in it.

**Comment by CyberBill** [comment]
Definitely!  Has anyone taken a look at the code to see how the inventory works?  I have a feeling it's just an ordered list of items, not a list of 'slots' that contain items.  I would figure it's better to re-implement it entirely to make it more in line with practically all other inventory systems.

**Comment by Meridian59** [comment]
Yes, it's just an ordered list.  Sorting is an improvement and would be fine, but I don't want it to look like all other inventory systems; I want it to remain true to the original look-and-feel.

**Comment by davidklaw** [comment]
Is this the sort of thing a pleb UI designer like myself could propose a solution for? It seems like the technical bits behind the scenes are something understood and it's the frontend experience that needs some thought, and I'd be interested in helping.

**Comment by qorkod** [comment]
Let’s please get this looked at to enhance the user experience. 

If you have a bardscroll inscriptionitem then use it, it’ll auto sort and appear at the bottom of your inventory - so the functionality is there. 

The user should be able to drag, drop, (ex: with arrow and movement similar to placing items in boxes and on the floor) place and replace the viewable inventory - like a tile system.

**Comment by marcelkauf** [comment]
Inventory drag-and-drop sorting was implemented on 112/105 years ago. I only found this commit since all forks are either a chaotic mess or switched to close source at some point. I have not looked into the details, but it should give an idea of how to do it: https://github.com/thuhuong2k/Meridian59/commit/f8f9bbd997ef6cefb2f31eb89ab5cb5dcef9fbeb

**Comment by jrotunda** [comment]
@davidklaw @marcelkauf thank you for the tip!

**Comment by davidklaw** [comment]
@Meridian59 We can close this!

Sorting added via #487
