### ISSUE TITLE
[PVP] 10 minute pvp flag changed to permanent until reaching a safe place, and long timer reduce on rescue

### ISSUE THREAD

**Issue by Kopfz** [Meridian59/Meridian59#271]
The ten minute lockout on escape spells, and the massive increased time to rescue do not serve the intended purpose--to give hunters a greater chance of catching pkers.

Suggest changing the flag to have unlimited duration, and only be removed upon reaching an inn, adventure hall, or safe within a guild hall. 

This would mean that pkers once reaching a safe place could teleport immediately, but pkers caught in side a merchant store or other non-pvp zone must either fight their way out, or wait out their hunters.

With this change, restore rescue timer as the increased fire time in unnecessary and serves no real purpose. 

Hunters get the opportunity to head a pker off, but if they fail, the pker has all tricks available immediately to disappear and continue with their wicked ways.

**Comment by jrotunda** [comment]
Grief style PKing isn't an issue anymore, not in a way that further changes need to be made to the game, but this is was a good idea for combatting problems then. If @Kopfz is around and has done this code it would be worth looking at.

If not suggest to close this issue.

**Comment by jrotunda** [comment]
Attempted address to this issue:

The rescue time is currently longer on 101 using rescuebasedelay in settings. 

Default is 15 seconds - which can wind up being up to 30 with low spell power.

After testing it's been lowered a bit, but higher than what players were used to (base delay of 2-4 seconds) for a while.

Actual set time will not be posted for gameplay reasons.
 
Those who are using it to escape pve/pvp combat can still in initiate retreat, escape and feel saved in the nick of time.

Cannot be used in PVP to immediately leave the field of battle without putting yourself at risk. 

Despite that and my initial comment - I like this idea if it's possible to implement, as it's nuanced, and feels like how being red / random used to be - where you'd be trapped somewhere and hunters are outside, and you have to go and face the music, logoff unsafely or wait them out. 

Pks being able to get around anywhere with Elusion has been a problem for along time as it puts a large experience gap between the PK and the new players mostly targeted in this way by sniping and vanishing. 

Do not think this takes away their ability to do so, but makes what they're doing have greater risk - the way it is now is risk free.

**Comment by davidklaw** [comment]
Is there still an appetite for this 10 years later?
