### ISSUE TITLE
Highlight special weapons

### ISSUE THREAD

**Issue by Serpentiel-zz** [Meridian59/Meridian59#274]
It would be a great help if special weapons would be highlighted in the "look at"/"pick up" window.
With a floor filled with 1000 weapons like you have often on Brax its nearly impossible to find them :(

**Comment by davidklaw** [comment]
@Meridian59 Is this implementation of highlighting magic items in the item list windows something you're open to? A change like this has been requested at least a few times and would seem to make for a nice QOL improvement given the piles and piles of loot that get produced when building. I'd volunteer to put a PR up and minimize the file changes.

https://github.com/OpenMeridian/Meridian59/pull/502

**Comment by Meridian59** [comment]
I can't really read that change, it's a mess of unrelated whitespace
changes.  Does it change the color of the item name in dialogs?  What
qualifies as "magic"?

**Comment by davidklaw** [comment]
I haven't looked deeply into the code yet, but the gist of it is that items with special attributes are given orange names in list boxes. That color is customizable under Options. Whether or not an item attribute falls into this category is handled by a new `IsMagicalEffect()` method. There's some other things going on I don't quite understand yet.

**Comment by akirmse** [comment]
This is done via the new (rare) etc. tags on items.
