### ISSUE TITLE
Make RecreateAll preserve factions, shrines

### ISSUE THREAD

**Issue by Meridian59** [Meridian59/Meridian59#29]
System.RecreateAll should preserve the state of factions and shrines.

**Comment by jrotunda** [comment]
There appear to be some fixes for this @davidklaw  as linked by @Serpentiel-zz

**Comment by davidklaw** [comment]
@Meridian59 What are your thoughts on [this implementation for flags](https://github.com/skittles1/Meridian59/commit/ed19967b2655d8ea938a0bc310ef94f0e314307e)? I confirmed flag factions aren't recreated today and preliminary tests show this works, but is there a more optimal/desired way of handling this?

**Comment by Meridian59** [comment]
That general approach is fine: get a list of state to save, recreate, then
reapply the state.  The particular implementation leaves something to be
desired, e.g. it would fail if there were ever more than one flag per
room.  There's also some duplication of existing code that can be avoided.
But it's the right idea.

**Comment by davidklaw** [comment]
Shrine recreate support added via #449
