### ISSUE TITLE
Problem in .\club when compiling

### ISSUE THREAD

**Issue by broodhill** [Meridian59/Meridian59#325]
There is a problem when trying to compile the source, alot of errors about the archive_static.lib when trying to compile .\club
When I changed in the makefile to replace archive_static.lib -> archive.lib I could compile without any errors.

I suspect it may be this commit that broke it
https://github.com/Meridian59/Meridian59/commit/09adf96dbedf17293ca4260fbb7d5213bd674e73

This is far beyond my knowledge so if anyone can take a look at it to see what is wrong. I do not know if using archive.lib may cause any other errors but it atleast compiles without any problems.

**Comment by Meridian59** [comment]
Can you say what error messages you're seeing?  It compiles fine for me so
maybe I just forgot to check something in.

**Comment by broodhill** [comment]
This is the error it produces.

Making in .\club
club.c
clubarchive.c
util.c
transfer.c
Generating Code...
archive_static.lib(archive_read_support_filter_gzip.obj) : error LNK2019: unreso
lved external symbol __imp__inflateInit2_ referenced in function _consume_header

archive_static.lib(archive_read_support_format_zip.obj) : error LNK2001: unresol
ved external symbol __imp__inflateInit2_
archive_static.lib(archive_read_support_format_cab.obj) : error LNK2001: unresol
ved external symbol __imp__inflateInit2_
archive_static.lib(archive_read_support_format_7zip.obj) : error LNK2001: unreso
lved external symbol __imp__inflateInit2_
archive_static.lib(archive_read_support_filter_gzip.obj) : error LNK2019: unreso
lved external symbol __imp__crc32 referenced in function _consume_header
archive_static.lib(archive_read_support_format_zip.obj) : error LNK2001: unresol
ved external symbol __imp__crc32
archive_static.lib(archive_read_support_format_rar.obj) : error LNK2001: unresol
ved external symbol __imp__crc32
archive_static.lib(archive_read_support_format_7zip.obj) : error LNK2001: unreso
lved external symbol __imp__crc32
archive_static.lib(archive_read_support_format_7zip.obj) : error LNK2001: unreso
lved external symbol __imp__inflateEnd
archive_static.lib(archive_read_support_filter_gzip.obj) : error LNK2001: unreso
lved external symbol __imp__inflateEnd
archive_static.lib(archive_read_support_format_zip.obj) : error LNK2001: unresol
ved external symbol __imp__inflateEnd
archive_static.lib(archive_read_support_format_iso9660.obj) : error LNK2001: unr
esolved external symbol __imp__inflateEnd
archive_static.lib(archive_read_support_format_cab.obj) : error LNK2001: unresol
ved external symbol __imp__inflateEnd
archive_static.lib(archive_read_support_format_7zip.obj) : error LNK2001: unreso
lved external symbol __imp__inflate
archive_static.lib(archive_read_support_filter_gzip.obj) : error LNK2001: unreso
lved external symbol __imp__inflate
archive_static.lib(archive_read_support_format_zip.obj) : error LNK2001: unresol
ved external symbol __imp__inflate
archive_static.lib(archive_read_support_format_iso9660.obj) : error LNK2001: unr
esolved external symbol __imp__inflate
archive_static.lib(archive_read_support_format_cab.obj) : error LNK2001: unresol
ved external symbol __imp__inflate
archive_static.lib(archive_read_support_format_zip.obj) : error LNK2019: unresol
ved external symbol __imp__inflateReset referenced in function _zip_deflate_init

archive_static.lib(archive_read_support_format_iso9660.obj) : error LNK2001: unr
esolved external symbol __imp__inflateReset
archive_static.lib(archive_read_support_format_cab.obj) : error LNK2001: unresol
ved external symbol __imp__inflateReset
archive_static.lib(archive_read_support_format_7zip.obj) : error LNK2001: unreso
lved external symbol __imp__inflateReset
archive_static.lib(archive_read_support_format_iso9660.obj) : error LNK2019: unr
esolved external symbol __imp__inflateInit_ referenced in function _zisofs_read_
data
archive_static.lib(archive_read_support_format_cab.obj) : error LNK2019: unresol
ved external symbol __imp__inflateSetDictionary referenced in function _cab_read
_ahead_cfdata_deflate
debug\club.exe : fatal error LNK1120: 7 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.EXE"' : return code '0x2'
Stop.

**Comment by Meridian59** [comment]
I may have forgotten to update archive_static.  Get the latest one and see
if that works.

**Comment by broodhill** [comment]
Great, it works now!
