### ISSUE TITLE
Projects not getting built - m59bind.exe for example

### ISSUE THREAD

**Issue by CyberBill** [Meridian59/Meridian59#326]
Just wanted to let you know that in my journey today to get VS2013 project files working, I found out that the "nmake all" failing ends up not building some other projects that would (should?) normally build fine, but since they aren't being attempted to be built, there are little errors creeping around in them.

As an example, in this effort I'm currently getting the m59bind.exe program building, and found that "nmake Bkeybind" will fail with an error saying:  fatal error LNK1104: cannot open file 'nafxcw.lib'   (or 'nafxcwd.lib').  Fixing this error gets it to build (with some warnings).

The remedy is pretty easy - just make sure that you install this Visual Studio 2013 MFC Library:  http://www.microsoft.com/en-us/download/confirmation.aspx?id=40770

(Note - I also had to remove the line that adds 'nafxcw.lib' to the LIBS, since it gets automatically linked already)

I think that we should add that install step to the Readme file, and maybe comment out the build step that is currently failing (Bupdater) - or fix it.

**Comment by Meridian59** [comment]
keybind should be the only project not being built, and the reason is
because MFC is not included with the free version of VS2013.  It's
intentionally not listed as a target under 'all' for this reason.

I didn't know that you could download MFC for VS 2013, though.  I'll give
that a try, and if it works, I'll update the LIBS for the project, and the
global README.  Thanks for the info!

I'd be happy to accept a change that fixes the warnings.

**Comment by Meridian59** [comment]
Hm, I'm unable to install the MFC library.  Looks like it requires a Pro
version of VS.  Having a Pro version is a big barrier to entry for many
people so I wouldn't want to add that requirement.

Can you send me a change that gets keybind building with VS 2013 Pro?  The
latest paid version I have is 2008.

**Comment by CyberBill** [comment]
Oh, interesting - I'm using the professional version of VS2013 myself.  (Perks of working for Microsoft!)  That link is just for the Multi-Byte version of MFC, so maybe there is a Unicode version you could install first/instead?

I did notice that it was just keybind failing to build after my post - it was just the first one that I got to and I figured there would be others.  I -do- suspect that maybe some others that do build aren't getting built, though.  makebgf, for example, I don't think gets updated.  As soon as it built, the resource build would fail.  I tracked it down to writebgf.c line 181 - there are two variables named 'len' in scope, and removing the 2nd fixed it.

I've got it building locally and I'll include the change with my branch/fork/pull request/I don't know the right lingo for "shelve set". ;)  The updater/club is the last project I need to fix.

**Comment by Meridian59** [comment]
I don't think there is a free version of MFC... I recall reading that while
investigating VS 2013.  Maybe drop a note to your employer :-)
https://msdn.microsoft.com/en-us/library/hh967573.aspx

You're right about the extra declaration in makebgf.  I bet that's been
there for 15 years.  I will fix it, but it's strange that it compiles OK
here and for everyone else who has tried it.  Somehow we have different
settings, or maybe the Express compiler has different defaults?

**Comment by cyberjunk** [comment]
Just a sidenote:
I think 'Keen' (treymd) reimplemented the keybind tool as C# forms application for the 103 branch (due to the issues discussed here). I have been zero involved in that project so I can't give you any further information. But it might be worth having a look:

https://github.com/Daenks/Meridian59_103/tree/master/keybind

**Comment by CyberBill** [comment]
Sorry that I haven't checked in my changes yet.  They're done - but I'm having a heck of a time getting GitHub to do anything useful for me.  Anyone else having issues with it thinking that files exist when they don't, or showing files as having every single line changed - even after double checking that the line endings are right?  It's very frustrating since there doesn't seem to be a help forum anywhere.

**Comment by CyberBill** [comment]
DONE!  Builds properly in my fork. :)

**Comment by Meridian59** [comment]
Seems like this is working as intended, since MFC isn't free.
