### ISSUE TITLE
VS2015 compatibility

### ISSUE THREAD

**Issue by cyberjunk** [Meridian59/Meridian59#331]
For compatibility with VS2015 have a look here:
https://github.com/OpenMeridian/Meridian59/pull/1104

The precompiled static libpng.lib is incompatible, so we decided to compile it in the build process.
The others are just trivial fixes for warnings not found by previous VS versions.

PS: No, we're not switchting to VS2015 right now, just making sure it's compatible.

**Comment by Meridian59** [comment]
Thanks for this!  I put in the warning fixes with a few changes.  In
particular, I want to avoid exotic printf parameters in blakserv because it
would make a port to Linux harder.

I'll think about what to do for libpng.  What you guys did sounds
reasonable.

**Comment by Meridian59** [comment]
Everything builds with VC 2017 now.
