### ISSUE TITLE
Subproject "blackserv" not compiling on Linux

### ISSUE THREAD

**Issue by 0xbaadf00d** [Meridian59/Meridian59#336]
Hi,

The compilation fail on Linux (I'm using the branch "linux" of this repository). The variable __main_thread_count__ is not declared

    14:34:23-zero-x-baadf00d:~/devel/Meridian59/blakserv$ cat /etc/os-release
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"

    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"

    14:35:12-zero-x-baadf00d:~/devel/Meridian59/blakserv$ make -f makefile.linux
    mkdir debug
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/main.obj -c main.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/loadkod.obj -c loadkod.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/class.obj -c class.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/message.obj -c message.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/object.obj -c object.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/sendmsg.obj -c sendmsg.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/roofile.obj -c roofile.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/bufpool.obj -c bufpool.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/ccode.obj -c ccode.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/channel.obj -c channel.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/list.obj -c list.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/timer.obj -c timer.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/session.obj -c session.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/loadrsc.obj -c loadrsc.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/blakres.obj -c blakres.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/roomdata.obj -c roomdata.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/commcli.obj -c commcli.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/string.obj -c string.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/async.obj -c async.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/loadgame.obj -c loadgame.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/game.obj -c game.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/term.obj -c term.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/account.obj -c account.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/loadacco.obj -c loadacco.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/saveacco.obj -c saveacco.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/savestr.obj -c savestr.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/loadstr.obj -c loadstr.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/nameid.obj -c nameid.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/time.obj -c time.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/dllist.obj -c dllist.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/trysync.obj -c trysync.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/saveall.obj -c saveall.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/loadall.obj -c loadall.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/synched.obj -c synched.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/motd.obj -c motd.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/admin.obj -c admin.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/garbage.obj -c garbage.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/kodbase.obj -c kodbase.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/savegame.obj -c savegame.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/user.obj -c user.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/system.obj -c system.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/resync.obj -c resync.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/gamelock.obj -c gamelock.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/config.obj -c config.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/apndfile.obj -c apndfile.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/admincons.obj -c admincons.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/builtin.obj -c builtin.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/version.obj -c version.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/systimer.obj -c systimer.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/memory.obj -c memory.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/intrlock.obj -c intrlock.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/chanbuf.obj -c chanbuf.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/debug.obj -c debug.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/saversc.obj -c saversc.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/adminfn.obj -c adminfn.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/table.obj -c table.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/parsecli.obj -c parsecli.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/rscload.obj -c ../util/rscload.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/crc.obj -c ../util/crc.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/md5.obj -c ../util/md5.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/maintenance.obj -c maintenance.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/block.obj -c block.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/stringinthash.obj -c stringinthash.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/intstringhash.obj -c intstringhash.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/files.obj -c files.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/sprocket.obj -c sprocket.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/linux-critical_section.obj -c linux-critical_section.c
    g++ -I ../include -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/linux-threading.obj -c linux-threading.c
    linux-threading.c: In function ‘BOOL InitMsgQueue()’:
    linux-threading.c:25:5: error: ‘main_thread_count’ was not declared in this scope
         main_thread_count = 0;
         ^
    make: *** [debug/linux-threading.obj] Error 1

**Comment by Meridian59** [comment]
I didn't even know that branch was there to be honest.  cc:ing the guy who
probably created it.

**Comment by Meridian59** [comment]
I never got the original sender's email address as part of this CC, but
yes, this certainly looks like at least some version of my linux branch.
The branch really only exists in my repo and hasn't even been merged in the
openmeridian project.  If he wants the most recent code it is here:
https://github.com/treymd/Meridian59_103/tree/linux

I haven't had time to work on it in a while but last time I did, it was
building and running (with some errors and various bugs to fix).

**Comment by treymd** [comment]
Ah, here we are!  Yes, try out the Linux branch in my repo as posted above.

**Comment by 0xbaadf00d** [comment]
Hi,

It seem your Linux version doesn't compile on 64 bits server.


    06:30:19-zero-x-baadf00d:~/devel/Meridian59_103$ git checkout linux
    Switched to branch 'linux'
	
    06:30:24-zero-x-baadf00d:~/devel/Meridian59_103$ cd blakserv/
	
    06:30:28-zero-x-baadf00d:~/devel/Meridian59_103/blakserv$ make -f makefile.linux
    mkdir debug
    mkdir: cannot create directory ‘debug’: File exists
    make: [makedirs] Error 1 (ignored)
    g++ -m32 -I ../include -g -x c++ -DBLAK_PLATFORM_LINUX -Wno-write-strings -o debug/main.obj -c main.c
    In file included from /usr/include/features.h:399:0,
                     from /usr/include/ctype.h:26,
                     from linux-types.h:1,
                     from blakserv.h:157,
                     from main.c:21:
    /usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
     # include <gnu/stubs-32.h>
                               ^
    compilation terminated.
    make: *** [debug/main.obj] Error 1


Maybe it could be interresting to move the dedicated server out of the client repository and port from C to other modern language like C++ (with CMake / Boost IO) or Java (Java NIO). It could be a great opportunity to fix architecture issue and provide a multi-os / multi-arch working server ?

**Comment by treymd** [comment]
Compiles with my 64 bit compiler just fine, though to truly take advantage of 64 bit we have many changes to make to the code itself.  You appear to be missing something in your build tree.

<gnu/stubs-32.h>

this file is not part of our project.

**Comment by 0xbaadf00d** [comment]
The compilation works well without the -m32 flag on compilation and linking stage.

**Comment by Meridian59** [comment]
The main branch compiles fine for me on linux with "make -f makefile.linux".
