### ISSUE TITLE
Port server to Linux

### ISSUE THREAD

**Issue by Meridian59** [Meridian59/Meridian59#34]
The big remaining pieces that need moving over:

- Make the build system work in Linux

- Replace Winsock with epoll() or a portable networking library

- Abstract and port FindFirstFile/FindNextFile

- Abstract and port asynchronous reverse DNS lookups (not strictly necessary, but nice)

- Remove or replace the GUI in the Linux version

**Comment by KyleCartmell** [comment]
Is anyone working on this?

**Comment by Meridian59** [comment]
See http://www.gilcon.net/m59forum/forums/thread-view.asp?tid=5225&posts=11&start=1.  Help is welcome.

**Comment by dalu** [comment]
created this hobby project, port server to Go
https://github.com/dalu/meridian59go
will probably not finish it
and it will need to be adapted for Go, the structs and functions
since Go allows for something like
```go
type accountNode struct {
id int
name string
password []byte
next *accountNode
}

func (a *accountNode) SetEncryptedPassword(password string) error {
     var err error
     a.password, err = bcrypt.EncryptPassword([]byte(password),12)
     return err
}
```

but yeah if anyone is interested in joining the fun, welcome to send PR

**Comment by Meridian59** [comment]
The checked-in code is capable of running the large saved game from server 101 on Linux.

**Comment by dalu** [comment]
how do you build on linux?
```
$ mv rules.mak.linux rules.mak
$ mv common.mak.linux common.mak
$ make
makefile:6: *** missing separator.  Stop.
```

**Comment by Meridian59** [comment]
cd blakserv
make -f makefile.linux

Do not move or rename any files.

**Comment by dalu** [comment]
there is no makefile.linux commited

**Comment by Meridian59** [comment]
You need to "cd blakserv" first.

https://github.com/Meridian59/Meridian59/blob/master/blakserv/makefile.linux

**Comment by dalu** [comment]
Thank you. I'm blind. :)
Compiles without error or warning with gcc 5.3.0 (arch) and 4.8.3 (centos7.1)
cheers

**Comment by SilenceM59** [comment]
Sorry to bump this thread but I am getting this error when attempting to build in linux:

`make -f makefile.linux`

```
....
Building spelitemsplit
Building swshard
Building token
Building totem
Building weapon
Building ranged
Building bow
Building lorebook
Copying kodbase.txt and kod include files
Copying .rsc and creating client .rsb file
/bin/sh: 1: ../bin/rscmerge: not found
```

**Comment by akirmse** [comment]
Try building in the "util" subdirectory first.  Sorry that's not clear in
the instructions; I will improve it in the future.

**Comment by SilenceM59** [comment]
Thanks for the quick reply!

I will let you know how it goes :)

I have another question for a different thread, but if it saves you some time:   Is it possible to "read" the savegame states in a readable state that can also be recompiled?  I'm not after passwords or anything like that (hopefully those are hashed), but more along the lines of cherry-picking for possible issues if the server ever crashes, or if I want to make some bold move to migrate all of the data to a different server.

**Comment by akirmse** [comment]
I'm not sure I understand your second question.  The save game file is
basically just a dump of all of the game objects.  You could certainly
write a program that would read it in and analyze it.  Combining all of the
objects from two servers would be quite difficult because there are
references to global objects like lists of all users, etc. that would need
to be merged somehow.  Missing even one of these would leave the game in a
fatally inconsistent state.

**Comment by SilenceM59** [comment]
Ok cool - Get back to you on the linux stuff in a bit. Thanks again for your help and keeping the game open source!

**Comment by SilenceM59** [comment]
Here's my latest output... 

```
mkdir: cannot create directory ‘debug’: File exists
../rules.mak.linux:6: recipe for target 'makedirs' failed
make: [makedirs] Error 1 (ignored)
g++  -I ../include -o debug/rscload.obj -c ../util/rscload.c
make: g++: Command not found
makefile.linux:19: recipe for target 'debug/rscload.obj' failed
make: *** [debug/rscload.obj] Error 127
```

**Comment by SilenceM59** [comment]
I ran `make -f makefile.linux` from the util directory

**Comment by akirmse** [comment]
This looks like the relevant line:

make: g++: Command not found


Do you have gcc/g++ installed?  That's the compiler that's needed to build
all of the C code.  I'm surprised that blakserv or blakcomp would have
built without this (did they?).

**Comment by SilenceM59** [comment]
I might not have gcc/g++ installed. This is being setup on Ubuntu 17.10.

I will look into those types of errors as I encounter them and maybe end up with a stable build.

I think also part of the problem is I have an already built blakserv.exe that I'm running, but wanted to eventually port to Linux. I am wondering if there's a conflict.

**Comment by SilenceM59** [comment]
Ok so I'm back with new errors.

This one looks like architecture issues.

Here's my aptitude list:

```
g++/artful,now 4:7.2.0-1ubuntu1 amd64 [installed]
g++-7/artful-updates,artful-security,now 7.2.0-8ubuntu3.2 amd64 [installed,automatic]
gcc/artful,now 4:7.2.0-1ubuntu1 amd64 [installed]
gcc-7/artful-updates,artful-security,now 7.2.0-8ubuntu3.2 amd64 [installed,automatic]
gcc-7-base/artful-updates,artful-security,now 7.2.0-8ubuntu3.2 amd64 [installed]
libcaca0/artful,now 0.99.beta19-2build2~gcc5.2 amd64 [installed]
libgcc-7-dev/artful-updates,artful-security,now 7.2.0-8ubuntu3.2 amd64 [installed,automatic]
libgcc1/artful-updates,artful-security,now 1:7.2.0-8ubuntu3.2 amd64 [installed]
```

Here's the makefile output:

Most importantly these two lines:

```
/usr/bin/ld: i386 architecture of input file `debug/rscload.obj' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `debug/rscmerge.obj' is incompatible with i386:x86-64 output
```

Full Output:

```
mkdir: cannot create directory ‘debug’: File exists
../rules.mak.linux:6: recipe for target 'makedirs' failed
make: [makedirs] Error 1 (ignored)
g++ debug/rscload.obj debug/rscmerge.obj -o debug/rscmerge
/usr/bin/ld: i386 architecture of input file `debug/rscload.obj' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `debug/rscmerge.obj' is incompatible with i386:x86-64 output
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
debug/rscload.obj:(.text$mn+0x1d): undefined reference to `_fopen'
debug/rscload.obj:(.text$mn+0x4d): undefined reference to `_fclose'
debug/rscload.obj:(.text$mn+0x9): undefined reference to `__chkstk'
debug/rscload.obj:(.text$mn+0xe): undefined reference to `___security_cookie'
debug/rscload.obj:(.text$mn+0x3f): undefined reference to `_fread'
debug/rscload.obj:(.text$mn+0x73): undefined reference to `_fread'
debug/rscload.obj:(.text$mn+0x99): undefined reference to `_fread'
debug/rscload.obj:(.text$mn+0xdd): undefined reference to `_fread'
debug/rscload.obj:(.text$mn+0xfd): undefined reference to `_fread'
debug/rscload.obj:(.text$mn+0x11f): undefined reference to `_feof'
debug/rscload.obj:(.text$mn+0x141): undefined reference to `_fread'
debug/rscload.obj:(.text$mn+0x1b6): undefined reference to `@__security_check_cookie@4'
debug/rscmerge.obj:(.text$mn+0x34): undefined reference to `_strdup'
debug/rscmerge.obj:(.text$mn+0x8b): undefined reference to `_strdup'
debug/rscmerge.obj:(.text$mn+0xa): undefined reference to `___security_cookie'
debug/rscmerge.obj:(.text$mn+0x6c): undefined reference to `@__security_check_cookie@4'
debug/rscmerge.obj:(.text$mn+0x23): undefined reference to `_free'
debug/rscmerge.obj:(.text$mn+0xe): undefined reference to `_malloc'
debug/rscmerge.obj:(.text$mn+0x78): undefined reference to `_fopen'
debug/rscmerge.obj:(.text$mn+0xba): undefined reference to `_fwrite'
debug/rscmerge.obj:(.text$mn+0xd7): undefined reference to `_fwrite'
debug/rscmerge.obj:(.text$mn+0xeb): undefined reference to `_fwrite'
debug/rscmerge.obj:(.text$mn+0x147): undefined reference to `_fwrite'
debug/rscmerge.obj:(.text$mn+0x15b): undefined reference to `_fwrite'
debug/rscmerge.obj:(.text$mn+0x174): undefined reference to `_strlen'
debug/rscmerge.obj:(.text$mn+0x18b): undefined reference to `_fwrite'
debug/rscmerge.obj:(.text$mn+0x19e): undefined reference to `_fclose'
debug/rscmerge.obj:(.text$mn+0x4b): undefined reference to `_strlen'
collect2: error: ld returned 1 exit status
makefile.linux:59: recipe for target 'debug/rscmerge' failed
make: *** [debug/rscmerge] Error 1
```

**Comment by dalu** [comment]
libc source installed? Rule of thumb, when building, especially on those source-omitted distros, always install the sources too.
On debian based distros they're usually named -dev packages.
Not sure if ubuntu 17.10 supports multilib. Personally I'm not touching Ubuntu. It might be the de facto standard but it's also... let's say there are better alternatives.
Btw since you're curious about the save files, whatever happened to the SQL storage adapter?
Wasn't that a thing once, someone wanted to extend the server to store data live in a SQL DB.
I wonder how that would work. Store as blobs? Or actually translate the game objects into fields?
Getting off-topic.
