### ISSUE TITLE
KOD Build/Rebuild/Debug Question

### ISSUE THREAD

**Issue by SilenceM59** [Meridian59/Meridian59#347]
Hi there :)

I have been making updates to the KOD for my server and for example, I am making updates to the Radius Enchantments in nomovon.kod - which rebuilds all of the monsters, etc.

Is there any kind of "sandbox" or faster way to test code that doesn't require rebuilding KOD?

I am asking here because you guys would know better than I would, and you may know that debugging / testing KOD takes hours due to the 2 to 5 minute rebuilds.

Any advice you can give would be stellar.

Thanks!
-Silence

**Comment by akirmse** [comment]
If you're making simple changes that you are sure don't require recompiling
any subclasses (e.g. you don't change the name or number of any methods or
properties), you can build just a single file with:

set TOPDIR=c:\blakston
nmake nomoveon.bof

in the appropriate directory

**Comment by SilenceM59** [comment]
I guess the question is.... When I change the operations inside of a function that many other subclasses are using, does that require all of those subclasses to rebuild?

I'm not changing the parameters or adding new functions, I'm just changing the function's behavior. 

So if that's the case, this would really speed things up for me.

Thanks for replying so quickly!

**Comment by SilenceM59** [comment]
This worked like a charm!!!

THANK YOU <3
