### ISSUE TITLE
Copyright / Trademark / Compliance / Population Regrowth

### ISSUE THREAD

**Issue by NHuebner1983** [Meridian59/Meridian59#348]
Hey guys :)

I have been in and out of the game's mechanics (even the Blakserv source itself) and I think I'm at least above the "intermediate" mark when it comes to being a Meridian 59 server administrator.

I will cut right to it.... I want to get players back to the game.  This is "YOUR" game, you guys made it.  I have been looking into Steam Network (it's the largest). Aside from any negativity anyone has against Steam, I just want to give Meridian 59 a chance to get some new players. I'm not asking you to help me get listed - I am mainly asking for permission to list the game to those kinds of networks to revive the community.

The game would be "Free-To-Play", it would be maintained, and if I put in the 100+ hours to get the game Steam Compatible, I would need to know that you have my back for listing it.

If there are conditions to this, whatever they are I will agree to. The server and client I am running are all open source already, and will continue to remain Open Source.

The Game itself I am planning to use is the Ogre 3D Client, because everyone on Steam is expecting DirectX games. If this is not the case and you think I could offer Classic (or should), then let me know.

So is this a possibility? If so, what are the conditions? All I need is for you guys to let me know you support my movement in rebuilding the Meridian 59 community, and I will handle the heavy lifting.

**Comment by SilenceM59** [comment]
Here are some of the responsibilities I would have to take on that I wouldn't expect you guys to have to deal with.. Keep in mind, everything would be open source, so you would have full access to everything I am doing (including the Steam wrapper).

 - Pay a fee to Steam for consideration & review.
 - Build the Steam wrapper for the game to be eligible for Steam.
 - Implement the Steam Trading Card system (not sure how that will work yet).
 - Find & fix all bugs in the game.
 - Build an interactive tutorial that's a bit more advanced than Raza's signs.
 - Revamp 3D effects in the game (such as using particles for spell casting, etc).
 - Improve the quest system to be an interactive overlay.
 - Build an Achievement System that can integrate to Steam.

It's a lot of work, again I'm not asking you guys to do anything but give permission. 

What I can return if things work out:

 - Admin account(s) to manage the game for the original game creators / copyright holders.
 - Open to any other requests you might have to make this work.

**Comment by Meridian59** [comment]
We submitted Meridian to Steam in 2012, and it was rejected (they don't
give reasons).  Is there any new evidence that they have changed their mind?

**Comment by SilenceM59** [comment]
I have started a Steam forum discussion to try to spark some answers. I will also reach out to Steam to find out why they rejected without reason.

I think they should be able to tell me what it will take to guarantee the game gets listed on Steam. I think that's more than fair. There's no reason why we can't meet their standards and jump on the wagon with them.

**Comment by HoldOffHunger** [comment]
I'm totally in support of moving this onto Steam.  Let the masses have it.

There's no reason it should be rejected, and I find it particularly odd that it is listed as rejected.  Their rules are listed here: https://partner.steamgames.com/steamdirect  I couldn't imagine M59 breaking any of those rules, except maybe copyright on artwork or something?

I have seen some very low quality free games on steam.  Just search on the filter of "price: free" and about half of the stuff there is clearly abandoned, one-off projects most likely with just one developer.

I would be amazed if this were rejected without any reason.  It's unfortunate that happened in 2012, but that is aeons away.  Today, Steam handles 60% of all global gaming sales.  It has to be more open.

**Comment by SilenceM59** [comment]
The only thing I can think of so far is the possibility of files being picked up as a virus.

Here's what we've got going on right now:...

 - Club.exe is picked up as a Trojan so we're only supporting Ogre.
 - MSI installer for our Visual Studio Installer project is coming back as "Unsigned" (will have to figure that out).
 - Chrome complains about the MSI Installer being "Uncommonly downloaded" with the Discard/Keep message.

If we move towards steam, most likely game updates would be handled directly through Steam. 

It's really stupid they rejected it without reason - I wish I was able to find out the real reason.

**Comment by SilenceM59** [comment]
@Meridian59 Good news, things have really changed since Steam was around in 2012.

Here's a forum discussion you might want to read a few of the responses from:  http://steamcommunity.com/discussions/forum/1/1696043806551832400/

If you guys want to try again, that's great, we can all play on the original M59 server. If you don't have time and want me to try and get the game published to Steam, let me know what we need to do to move forward.

**Comment by SilenceM59** [comment]
If you guys decide to do a Steam submission, would it be possible beforehand to collaborate a few major things that can help bring all of the server owners together?

I was thinking, most games have multiple servers right.. Usually they are all on the same rules too. Well maybe we could have a Server List when you login and it shows how many people are on, how many people have registered, etc.

I am not being greedy or anything, but listing the game on Steam is the dream of each matured server owner (mine has been running for only 1 month) but I have been trucking forward with updates that make the game Steam-worthy in today's light.

**Comment by GarAdminTools** [comment]
103's on board with this. We've worked with Silence for awhile now and he's done some pretty great things for Ogre and his 115.

**Comment by akirmse** [comment]
We're going to have to read up on Steam's conditions and see which version
makes sense to submit, if any.  This might take awhile.

**Comment by HoldOffHunger** [comment]
As mentioned by GarAdminTools, "$100 is all you need".  This ARS Technica article (#2 google search result for "submit game to steam") says pretty much the same thing: https://arstechnica.com/gaming/2017/06/want-to-get-a-game-on-steam-100-is-all-you-need/

**Comment by SilenceM59** [comment]
@Daenks If you decide to do that again, let's team up on this one? I think the updater would work best if it had a "chunk" feature which could download the full update in chunks of 10% (zipped) when it needs to pull more than a certain number of files.

**Comment by SilenceM59** [comment]
@akirmse Just remember you have a lot of people here that can help and want the same thing you do - to get the game back out to the world. So if it's a matter of brainstorming up a new and improved Meridian 59, let's all work on it together to reach the goal.

Something I was recently spewing into Gar's ear through Discord about the possibility of reworking Blakserv to behave more like a modern day game server, without system saves, etc. There's plenty of good ideas floating around that we could help work on if you chose a direction.

**Comment by NHuebner1983** [comment]
Great job pushing to Steam! I'm already signed up.

Can't wait to see the game grow again, thank you!
