### ISSUE TITLE
The Sun and Moon don't appear in Hardware Renderer

### ISSUE THREAD

**Issue by Meridian59101102103** [Meridian59/Meridian59#350]
I don't know how I never noticed this before, but we can only see the Sun and the Moon on software renderer mode. That's... sort of a big deal, immersion wise. Does anyone have any idea how to fix this?

**Comment by Dirhai** [comment]
Sun and the Moon really adds to the immersion i would love to see a fix on this

**Comment by davidklaw** [comment]
I wouldn't have a clue as to how to address this one, but +1 to this.

**Comment by jrotunda** [comment]
Note: The Sun And Moon are their own class of object and are not part of the background.bgf and are still moving around in the sky whether the player can see them or not.

The objects themselves work and can be viewed by putting them in rooms or changing art of other resources without software render / but they are not being placed in front of the background .bmp, so we can't see them.

The moon and sun have gameplay impact: 

* Being able to tell the time naturally by looking into the sky - a huge amount of players don't know the time anymore, seeing them really helped.

* Riija SpellPower is directly affected by how high the Moon object is in the sky and helps them to to see how strong their spells are, drastically impacting Morph, Elusion, fizzles, etc.

* Looking at the sun dazzles the player and is a cool effect that is going unseen.

The code doesn't show any difference between software rendering and the "open GL" 3D-dynamic lighting graphics rendering for these objects.

**Comment by akirmse** [comment]
It looks like this was simply never implemented in hardware rendering.  Here's the implementation in the software renderer for reference:

https://github.com/Meridian59/Meridian59/blob/d2c51988542bc8f325d1b484cdc66933cbc9491c/clientd3d/drawbsp.c#L4029
