### ISSUE TITLE
Bug: Room: Raza Mausoleum generates mummies over its max monster setting 

### ISSUE THREAD

**Issue by qorkod** [Meridian59/Meridian59#381]
The MAUSOLEUM (rid newb6) in Raza will continue to spawn mummies no matter what the monster maximum setting is for the room as long as a user is present. Hundreds of mummies will spawn. 

To reproduce, log in to a server with Raza and go to the Mausoleum. M

Set the GEN PERCENT from 1-100 and a Max over 10 (to account for the automatic generated end puzzle monsters and any pit monsters in the entrance area). Wait and observe that mummies will continue to spawn over the maximum. 

Saving a new setting doesn’t stop the behavior.

It’s expected the room not continue to generate more monsters than its maximum amount setting in the object code for the room on a live server.

**Comment by davidklaw** [comment]
Is this still a reproducible issue outside of 101? In my development environment, I waited 30 minutes and `piMonster_count` only hit 21 (with a `piMonster_count_max` value of 20). I tested on 101 and did experience an ever-growing number of monsters.

What is server 101's `piMonster_count_max` for `Guest6`? For `newb6`?

**Comment by jrotunda** [comment]
When the boss room resets, the max monster count for the room goes up by 5.

To reproduce, finish the boss chamber. 

Look at "max monster count" in $admin. 

Exit the chamber completely by going up the steps and back into the maze.

When the boss room resets - door closes, pillar goes back up, mummies respawn - the max monster count goes up by 5. 

This will continue indefinitely unless changed manually by an admin. I've logged on and seen this room with a max monster count of over 1000 after a long period of time (and many newbies).

**Comment by davidklaw** [comment]
Thanks, that was helpful.

I've found that the max monster count increases by 1 each time one of the levers is pulled. I don't know the reasoning behind this, but we can see here that `SlamTimer()` (called when the door slams shut) is increasing the max count. Does anyone know why this might be?

```
SlamTimer()
   {
      ptDoor = $;

      if GetTime() > 59871006
      {
         piMonster_count_max = piMonster_count_max + 1;
         debug("New piMonster_count_max: ", piMonster_count_max);
      }

      Send(self,@SomethingWaveRoom,#wave_rsc=guest6_door1_rsc,#what=poLever1);
      Send(self,@SetSector,#sector=SECTOR_DOOR,#animation=ANIMATE_CEILING_LIFT,
           #height=84,#speed=128);

      Send(poLever1,@SetSwitched,#switched=FALSE);
      Send(poLever2,@SetSwitched,#switched=FALSE);

      return;
   }
```

**Comment by davidklaw** [comment]
I don't see any adverse effects from removing this logic and incremental addition. I'll put in a PR. Once it's removed the maximum count will never change, however, `piMonster_count_max` is a bit disingenuous. The room needs to spawn 5 pit mummies and will do so even if it takes the room over it's max monster count. Therefore, you can expect to hit 25 at times.
