### ISSUE TITLE
Rented Rooms: Item: Pet Dragonfly Cage can be placed but is unfinished, missing life cycle and storage feature.

### ISSUE THREAD

**Issue by qorkod** [Meridian59/Meridian59#383]
The Pet Dragonfly Cage (dflycage.kod and roomcage.bbg) features 5 stages:

#            1 egg in nest
#            2 sitting in cage
#            3 preening A 
#            4 preening B (Animated Flying)
#            5 empty cage

Currently, if you place a Dragonfly Cage it'll only stay at the Empty Cage state, and doesn't do anything beyond take up room, despite costing resources to create.

The code for the cage is unfinished and lacking options to utilize the the available resources and animations with this feature.

It's expected  that you be able to bring a Dragonfly Queen from the wild, into the room, and leave it stored in the cage where it would presumably heal its HP faster than normal, and stay loyal to the master, ready to be released, without it following them around and dying every time they log on. 

If the Queen dies and the cage has that Dragonfly Queen as its last occupant, an egg should then appear in the cage - making that the 5th stage, not the 1st, and allowing someone that completed the Dragonfly Queen capture to have a constant brood from that point forward as long as the room is maintained. 

Its expected that the cycle (ex: piHatchTime - INT 1 - ???, each +1 INT equaling a 24 hour day) from egg to hatching be a setting in in dflycage.kod, and after a set time period, an egg would appear in here after initially capturing and placing a Dragonfly Queen, but only after that original Queen dies or is lost.

**Comment by jrotunda** [comment]
This isn't so much an issue as it is a fun FR (Feature Request), it requires additional (maybe extensive depending on how creative) design work and should be tied to a couple other classes (CLASS MonsterPet) for a cohesive little bit of an endgame feature addition in the next patch 

It would go well with the patch introducing Ko'catan rentable rooms.


TBC (to be closed) -
