### ISSUE TITLE
Room: Spider Nest room .kod doesn't allow room lighting adjustments from light to dark

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#408]
The Spider Nest is set to "dim light", but casting light/darkness or changing its values in $ doesn't affect the textures or environment.

It's expected this room be able to be affected like most other outdoors areas, and making it lighter or darker doesn't change any aspect of the room other than make it look better and match the darkness level of other indoor caverns.

Note: This issue affects a handful of areas. I'll be putting these up individually over time. 

Once fixed it will allow the textures and game world to look cohesive, make good textures pop, soften the appearance of pixels and hard edges, and make it feel more immersive (and scary at night without using a light source) in its environs with the use of dynamic lighting, object and appropriate indoor/outdoor values.

**Comment by davidklaw** [comment]
Not only are the room's sectors unaffected by ambient light (and therefore these spells), the room itself has a rather high light level for being an underground cavern.

It's currently LIGHT_DARK (124) and I recommend LIGHT_MIN (0), which can then be lit by dynamic light sources or perhaps braziers paired with the skeletal remains of past explorers? Anyone have a preference?

```
% Ambient lighting constants
% Constants for natural level of light in the room.
LIGHT_MIN = 0
LIGHT_VERY_DARK = 84
LIGHT_DARK = 124
LIGHT_NICE = 164
LIGHT_MAX = 255
```

**Comment by akirmse** [comment]
Would LIGHT_MIN make it pitch black in the software renderer, outside of
lighted sectors?

**Comment by davidklaw** [comment]
Hadn't considered software yet, but will now. But as far as baseline a baseline for both, I'm thinking dark (but not pitch black) is appropriate.
