### ISSUE TITLE
Entering a newly created rented room causes a Resource Error; Game Change dialogue window appears

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#419]
When renting a new room from any inn, when the user opens the door to the room for the first time, a "The game has changed" dialogue window will appear on the UI asking if a Y/N question to download new files.

If YES, they're disconnected from the server. If NO they can stay online. 

The room will not cause the dialogue error to appear again after selecting NO, but they can cause it to happen if renting a room from another inn for the first time

To reproduce:

1) Go to any room keeper who rents rooms (currently Barloque, Marion or Kocatan) with a character who doesn't currently have a room at that inn.

Using DM or admin, type:
go rid_kocinn 
/ jasinn 
/ marinn

2) A Gold Key will be created in your inventory. Immediately go to the front of a valid room door in the Inn and USE the new Rentable Room key object (note: space doesn't open the door, since the rooms aren't connected you need the key at the door hotspot)

3) The dialogue box appears simultaneously as the user loads in the room. 

4) Select YES. 

5) If hanging at the character select window, manually disconnect.

6) Log back in to the character who was disconnected.

7) Select NO when the dialogue box appears again.

Users will be unable to play until they select NO. 

This occurs on 101, 102, and any test server using the current code.

[Included screenshot is from @davidklaw]

Notes:

This is possibly caused by the create function of CLASS RentableRoom, and the player object entering another Class/object, not a .ROO, 

If you place certain objects inside others, it can seemingly delete it one or both objects, but once this is a done a call to delete does NOT work and there are duplicate or unknown resource errors. This doesn't affect all classes and is a separate issue but the RentableRoom class is directly instigating this issue because they're Objects, not rooms.

**This may be connected to a larger issue with the way the server handles calls to delete classes and objects and fixing one may fix both**

The rentable room is not connected to the game world as a set .roo, but a dynamic object paired with two other new objects [CLASS MINT and CLASS (Room Bell name?) that players can go inside of with a set of variables.

When doing DMStartTour, the rented rooms
are visited first as they were just made on the live servers. 

When deleting a room: The room will call to delete when rent runs out, and there isn't a known error with rooms expiring in the manner. 

RentableRoom also creates RentableRoomKey, similar to how Lich and DeadLich exist simultaneously. 

There should be the same number of each class. If this number is off, that indicates another resource error on a server.

If you rent a room, then there is a system save, the new room should now be able to be entered normally due to the way resource updates work.

![image](https://user-images.githubusercontent.com/2608213/205827942-e8526984-9ca5-4c96-8cab-8a3ded412af8.png

**Comment by akirmse** [comment]
The dialog box was a side effect of a bad compilation setting.  It's gone now.
