### ISSUE TITLE
Missing Texture: Ancient Smuggler's Crossing

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#422]
There are missing textures on the UPPER WALL of the Ancient Smuggler's Crossing.

1) Entering from Barloque Sewers - look up while walking down the first hallway. 

Three wooden boards on the ceiling are missing textures on one side facing South in Overhead/Map view.

Room: 
sewking.roo
rid_sewking

[needs screenshot]

**Comment by TheDiggie** [comment]
![image](https://user-images.githubusercontent.com/8981364/208283427-34274a19-c387-424b-90d5-549407bf25fb.png)
