### ISSUE TITLE
Missing Texture: Avar Village

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#423]
The majority of border of the beach along the ocean is missing the LOWER WALL texture, allowing a user to see thru the floor.

Room:
KE4.roo
rid_ke4

[needs screenshot]

**Comment by TheDiggie** [comment]
![image](https://user-images.githubusercontent.com/8981364/208281556-37cb03dc-8881-4325-9216-b4bc75002e94.png)

**Comment by TheDiggie** [comment]
I'm not sure what witch craft the room is made with. if i open this map and then save it (changed NOTHING) the ocean is removed, the ocean doesn't have its own sector and i don't see anything in the maps kod that accommodates for this.
