### ISSUE TITLE
Missing Texture: Raza Mausoleum missing Upper Wall near water pit

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#424]
In the Raza Mausoleum, while going up the steps from the small water pit in the SE portion of the room, there is a missing UPPER WALL texture as the top of the staircase touches the next level of floor texture.

The user is able to see through the entire map here.

Note: This doesn't appear missing in the mirror variants of this room, Hazar Mausoleum (guest6) or Resting Place of Marion's Ancestors (Marion Crypt 1)

Room:

newb6.roo
rid_newb6

**Comment by davidklaw** [comment]
![image](https://user-images.githubusercontent.com/467443/208278685-402fffc6-4cc8-4cf5-ad7f-b9f1e071414f.png)

**Comment by davidklaw** [comment]
![image](https://user-images.githubusercontent.com/467443/208278699-943e3f8d-c067-42d4-a0af-e7d9c22f913e.png)
