### ISSUE TITLE
Floating Texture: East Ende

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#425]
In the East Ende, there's a noticeably large floating ground texture directly above the door/exit to the Tos Adventurer's Hall.

**Comment by davidklaw** [comment]
Outside Adventurer's Hall:
![image](https://user-images.githubusercontent.com/467443/208278629-fd855237-97e4-4689-916a-2f90b07e76d8.png)

Nearby Tos Bank:
![image](https://user-images.githubusercontent.com/467443/208278615-db266e80-a249-42ea-a1bb-3fc889de0e90.png)

**Comment by TheDiggie** [comment]
![image](https://user-images.githubusercontent.com/8981364/208280991-c61c3546-ea09-46b3-9515-30449f56a295.png)
