### ISSUE TITLE
Graphics: Player names above head show [1] integer displaying as [ ' ]

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#430]
The players name is showing a ' instead of a 1 in their name in the above head name display. 

This only affects the overhead name display.

Their name is fine on The Who List and in other text areas.

![image](https://user-images.githubusercontent.com/2608213/206599217-d409a895-7e10-4907-97d4-5696589215a1.png)"

**Comment by akirmse** [comment]
Fixed by https://github.com/Meridian59/Meridian59/commit/cbd8ad63fc11ad10e88723aecaba367ad71d647f
