### ISSUE TITLE
Crash: Passive Object: Wire Cage causes a room to not load using "group 4"

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#464]
The Dragonfly Cage, which is its own unique object and not an ornamental, has 4 varying looks, will crash a user and cause a room to not load when they attempt to log back in.

The item currently can be purchased by players to place in the rentable rooms with four heart stones.

The passive object item has 4 views currently that can be set manually changed in admin mode from the $ window:

0 - Empty Cage: the only view players see now 
1 - A nest and dragonfly pet egg
2 - Hatched, perching dragonfly pet
3 - Dragonfly pet rocking on perch

Setting the group to 4, or any int above 3, will cause an immediate crash when the screen is reloaded. Logging back into the screen will cause an indefinite hang. The room will not load again unless the group is 0-3

To reproduce:

1 - From a room
with a low ceiling, in $ on your server; Create o dragonflycage
2 - Send object [your room object] newhold what object [# you just got for the dragonflycage]
3 - **Refresh Cage Object**
4 - Show O [your object #] then click MOVE; note your Row and Column
4 - Show O [cage#] and move it close to you 
5 - Change the GROUP on the Cage from 0 to 1, 2 or 3
6 - Type reset in your chat, or hit invalidate date to reset and reload your view of each new frame of art as you change the group #
7 - Change the group to 4, then reload
8 - Crash.
9 - Log back in on an another profile and teleport to the room 
10 - Notice the room loads and you will be in it, but the view will not load, you will hang indefinitely, and will not be able to use $
11 - Show the dragonflycage object again from another profile (show list of passive objects to see the object in the room if you didn't note the #)
12 - Change the group back to 0-3 and the room will load again 

Note: This crash can't be reproduced at this time by players, but can become an issue for Admin / DM, and whenever further work is done on the dragonflycage or "dragonflypet", the currently unused active object that would hatch there.

**Comment by akirmse** [comment]
> 1 - From a room with a low ceiling, in $ on your server; Create o wirecage

> create o wirecage
Cannot find class named wirecage.

Did you mean DragonflyCage?

**Comment by jrotunda** [comment]
Yes, sorry, will
Update - "Wire Cage" is the in game name of the resource, "dragonflycage" is the class.

**Comment by akirmse** [comment]
I looked into this and I believe the issue is that the DragonflyCage does not have an inventory animation, so it results in an error if it's in your inventory.  This makes some sense, as it returns false in response to ReqNewHold.  A similar error would likely result if you tried to put a tree in your inventory, for example.

> 5 - Change the GROUP on the Cage from 0 to 1, 2 or 3

I don't see a property called GROUP on DragonflyCage.  There is, however, a property called piState whose legal values are 0 through 3.  4 is not a legal value, and would definitely result in protocol errors.

So I think this is just the result of the incorrect use of admin mode.  Correct me if I don't understand what this object is for.

**Comment by jrotunda** [comment]
Yes, it's piState, if the value is made to 4 in admin mode and it's only to occur that way. 
It doesn't have any purpose other than decoration for the rentable room, attainable with 4 heart stones - but doesn't do anything after that (someone could always take a look at that separately)

I'm okay with closing this given that it's admin only, thanks!

**Comment by akirmse** [comment]
Please be careful with admin mode!  If you want to do experiments, use a local server rather than production.
