### ISSUE TITLE
Gameplay: Spells: Arena: Player summoned Monsters don't move around or fight

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#467]
If a player casts Evil Twin, Apparition or Reflection in the arena, their summoned creature will stand in place and not do anything.

Expectation: 

Reflections to aggro on their masters attackers.

Apparition and Evil Twin minions to immediately aggro and chase targets until killed or user runs out of mana (respectively)

Players to be able to use their abilites mostly as they would outside the arena.

To reproduce:

* Go to the Tos Arena of Kraanan (go rid_tosarena) with two different characters 

1) DM Get Spells for Reflection/Evil Twin/Apparition and DM Immortal (skipping casting requirements)

2) Say "traditional", "champion", and "challenge" to get the two characters into the arena 

3) After the fight begins, cast evil twin and apparition on the enemy target

4) Note the behavior of the evil twin and apparition.

5) Cast reflection on yourself.

6) Have the enemy attack you to aggro the reflection

7) Note the behavior of the reflection.

**Comment by davidklaw** [comment]
This was fixed by #588

**Comment by davidklaw** [comment]
@Meridian59 This can be closed, as it was fixed by #588
