### ISSUE TITLE
Items: All Spell Scrolls use the Shal'ille insignia instead of their respective school.

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#472]
The spell scrolls, which include flash, dispel illusion, light, darkness, forces of light/truce come from 5 of the 6 spell schools, excluding Jala which doesn't have a scroll for its spells.

In the resources, there is art for Kraanan, Jala, Qor, Faren and Riija insignias.

 This art is the same for Ground Group, Inventory, and Examine view.

This is how and where the current scroll art is used and what they look like:

Scroll 1 / Love letter / personal letter / war letter - A plain scroll with a ribbon, no insiginia
Scroll 2 / Justicar-Royal Ballot - A scroll with a J symbol

Scroll 3 - Unused - Unknown Graphic
Scroll 4 - Unused - Unknown Graphic

Scroll 7 Shal / used for all spell scrolls!

- **Scroll 5 Kran / used for "recipescroll"; not used for Kraanan scrolls
- **Scroll 6 Qor / Not Used****
- **Scroll 8 Faren / used for "necromancerwarningletter" which is DM made only, not used for Faren scrolls
- **Scroll 9 Riija / used for "scamletter", not used for Riija scrolls**
- **Scroll 10 jala / used for "Dresspattern", not used for Jala scrolls as there are currently none****

Currently all spell scrolls use the Shal'ille Insignia, and some of the other school insignias are never seen - Qor or Faren - or seen rarely, Jala/Kran/Riija.

Besides not using available and appropriate art resources, this leads to confusion to this day over whether or not you have a Dispel Illusion or a Discordance scroll, which use an identical colored ribbon. This is confusing and also takes away agency from a player who opens a scroll to see what it does and learns it, players who don't have magic to reveal (a big ask for them to reveal a paltry, one time use, low spellpower item)

Expectation:

The spell scrolls for Qor, Faren, Kraanan and Riija to have the insignia of the school upon them, giving the player a better idea of what spell the scroll might be.

**Comment by jrotunda** [comment]
Thanks @adrienlaws That's an additional issue.

- NOTE: **All scrolls do not use the correct ribbon color when opened** and should/could be matched up. 
There is no bug/issue written for this individually yet for me to link to here.

You could perhaps headcanon that the ribbon is white on the other side of the ribbon.

This issue is for the spell scrolls specifically dropped by Creatures (and perhaps used for **TBD**)
- **all** of these Scrolls, when closed appear as the Shal'ille scroll with that Insignia, and do not show the Insignia for the Riija, Qor, Jala, Kraanan and Faren **schools.**


Expected Behavior:

1) Found scrolls to have **no** insignia, only have a colored ribbon. 
2) Found scrolls to have the insignia that matches each spell school (designed, created *unused* art attached above by @adrienlaws)

 **If** 1, keep note of and/or further allow:

3) A spell/skill/use scroll created using an in-game method (for example, an _inscription skill, spell, DM or NPC feature_), should create spell scroll with the Insignia of the school or function it belongs to; use existing art assets specifically created to display them. (_this feature is currently unavailable_)

_Up the @Aesica alleyway...?_ 
_@CardiovascularMike Maybe you'd like to take a glance at this too as it ties in to possible  "Bardy Business"_ 
🎻📜🖋🎶⚔ (%% first and last time I use emoji here, promise - JR)

**Comment by Gar103** [comment]
I don't believe we ever see the opened spell scroll image, scrolls are consumed on use

**Comment by jrotunda** [comment]
Fixed in #700
