### ISSUE TITLE
Item: Heal Wand: Item needs rebalancing

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#473]
Currently, you can quickly use a heal wand by highlighting the heal wand in your inventory, then pressing TAB and SPACE while aiming at your character's profile on the top of the UI, to go through a wand in seconds. Some users have this down to a terrible artform. It's demoralizing to face an enemy who spams these wands and goes up 30-50HP, which is a lot to suddenly be able to do, with no repercussion other than not being able to carry 4 more mushrooms.

Stats below for both items to compare:   

    Flask                                 Heal Wand
   Class: Healer                     Class: SpecialWand
   viBulk = 25                       viBulk = 20         
   viWeight = 20                   viWeight = 25    [Propose raising weight to 80, making them as heavy as a weapon like the bow]
   viValue_average = 60       viValue_average = 200 [Raise value, promote selling them so they don't wind up being harvested]
   piHeal_min = 5                 piHeal_min = 2
   piHeal_max = 10              piHeal_max = 10
   viFilling = 15                     viFilling =  N/A, not consumable

In my experience, this has been a problem going back to late 3DO era, and is almost comical if you have an enemy who has all heal wands and 30HP - they will be able to outsurvive in a way that goes against other expected game mechanics, such as how the flasks were made to be filling, and heavier.

- The Flask, which heals for as much as the heal wand, has a maximum use of 5-6 flasks on an empty stomach. The flask, a small bottle, also weighs more than the wand. 

- One wand weight LESS than a flask - there is no reason to use a flask except for that "guaranteed" 5hp heal, but the weight and filling limit makes their use more prepatory, and sacrifices must be weighed - to eat an inky/mint, or to save room for a flask?

- Players have complained about the wands for years, and has led to "well if you're doing it then I'm doing it!" PvP, which makes the experience less fun, embittering towards their enemy, and dissatisfaction with PvP combat.

Expectation: 

The Heal Wand to have a limit on its use, similar to the flask, by weighing more and causing more careful planning and inventory management.

Rather than an arbitrary limit to the amount of them you can carry, which still promotes loading up on the available maximum, doesn't feel right and takes away from the player's ability to organize their inventory, the wand should weigh a little more, which promotes careful inventory planning, and still allows a player to load up on them for other reasons, backup, etc, but reduces their overuse in PvP situations.

**Comment by jrotunda** [comment]
Needs:

Slight adjustment to heal wand weight - suggest making item 80 bulk, as heavy as a bow. 

Reduce chance of heal wand dropping in troll treasure template.

**Comment by Aesica** [comment]
Honestly I really don't like the idea of making a wand be huge and weigh a ton, just to make it more inconvenient in pvp, because this makes it more inconvenient in *all* cases.  Instead, what about a fix that reduces the amount healed when used on a player with the "has pvp'd recently" flag active?  Something like 50% or even 25% of their normal amount would be good.

This way, they can still be used in pve without taking up massive amounts of precious inventory space.

**Comment by jrotunda** [comment]
That sounds great and better than my idea, if you can figure out how to code that - 25% would be a good place to start.

**Comment by Gar103** [comment]
This is definitely bigger than a simple numbers change. The real question here is, "How do you want the healing and HP system to work?"

There needs to be a cohesive overall picture of this system, including Shal's heals, and even Qor's vampiric drain and vamp wands. For example, the more heal wands get nerfed, the more powerful Shal becomes. Imagine being a Qor or a PF if heal wands don't work in pvp, so you've got 150 HP, but your shal opponent has 600+ HP. Every time you ding them down a bit, they flash off a major heal, and you have to start all over again. That feels awful.

Heal wands also effectively lengthen combat to a point where players can actually fight back. If you get blind/held/etc, there's literally nothing you can do but run around like a headless chicken... _unless_ you've got heal wands, which lets you survive long enough for opportunities to turn the tables.

So, currently, heal wands basically act to convert Might (carrying capacity) into extra HP. That extra HP acts as a crutch for the entire PvP system, allowing prepared players to survive into combat rounds where things actually get meaningful. I'd be very careful, the whole thing could come apart by changing this without a big picture view.

**Comment by jrotunda** [comment]
This issue does not seem to be as important to players or as much of a negative during PvP gameplay as it used to be. Appreciate the added design insight and general use feedback from @Gar103 

Closing this as by design for now, with some closing thoughts:

- Reduce the chances of them dropping from easily farmed by (faren/riija pks) and from trolls (..._see what I did there? ;_ )
(@Aesica Possible TreasureList Update seed)
- Make the heal wands appear more for newbies in their travels (from signet returns or early quest rewards, for sale from or an added quest in Raza from the elder, for sale from Izzio, dropped from the Raza pillar), heal wands are a beneficial and non-destructive item to help develop skill in interface mechanics when using wands on both the user and other targets
