### ISSUE TITLE
client child windows open on other monitor

### ISSUE THREAD

**Issue by adrienlaws** [Meridian59/Meridian59#546]
## Description
If you open the client on the non-primary monitor (2nd monitor) then the sub-windows that open will open on the primary monitor.

## Suggested Fix
Make the child windows of the client open on the monitor that the client is in

## Example Image (capturing across monitors)
![Meridian_VCkhUHB6ZO](https://github.com/Meridian59/Meridian59/assets/4023541/b8217999-13f7-4a26-bfe7-5d6fa1f6304f)

**Comment by akirmse** [comment]
I don't have multiple monitors to debug this, but FYI here is some Microsoft documentation that seems to imply that the dialog should appear on the same monitor as its owner.  These dialogs are usually created by the function DialogBoxParam, with the main window passed in as the owner, so you'd think it would work.

https://learn.microsoft.com/en-us/windows/win32/gdi/positioning-objects-on-multiple-display-monitors

**Comment by akirmse** [comment]
Fixed by #608
