### ISSUE TITLE
NPC: Text: NPC Welcome dialogue doesn't trigger when users enter the room.

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#593]
Most NPC's (and every NPC that has a shop) have a line of dialogue in their resources that is said individually to a user when they enter the room. 

This dialogue is said as a welcome and is affected by the NPC mood and the players hometown, liege, or innocent/outlaw status.

Note: It's a 'say', that only each user hears. 

This dialogue isn't triggered when users enter the room. 

(Looking at the code, I can't see why)

**Comment by davidklaw** [comment]
@Meridian59 Can be closed as fixed via #775
