### ISSUE TITLE
Item: Magic Weapons Disabled

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#611]
The following magic weapons currently drop but have been disabled since 2004-5. 

The reason for them being disabled according to development notes by Brian "Psychochild" Green was that the damage modifiers, which range from minor to major using terminology on the weapons (notable, potent, damaging, crushing, enormous), were too effective at the high range.

The weapons were disabled before other PvP and gameplay changes, including AI enhancements to Reflection (a weapon held by the user is also held by the reflection).

Guild Hall - 15 variants, including GuildHall15 (Brax); does extra damage when used in the Hall (note: meant for hall takeovers, war, etc)

Faction - 3 variants - Jonas, Princess, Duke;
does extra damage on anyone.

Colhorr - (must be "master" with high % of weapon skill);
does extra damage on anyone.

Justice - Can be wielded by white named players only; does extra damage on outlaws and murderers.

Expectation:

These weapons, which occasionally drop from all variety of monsters, should work and offer a reasonable combat bonus, but nothing that can be considered unfair or imbalanced.

Suggestion:
Make the weapons function similar to Spell casting Weapons such as Blind, Hold and give a damage bonus only occasionally per hit roll factors, and not every swing.

**Comment by CardiovascularMike** [comment]
I agree with this suggestion but I would add: 

Suggestion 2: Stop new Guild Hall weapons from being dropped by monsters.  These weapons have no use-case.  Imagine your hall is being taken over - time is of the essence and you have to fight quickly.  The last thing you want to do is open your guild hall's treasure chest storage room and dig around looking for your +2 damage defense bonus sword.

Also:  There is a class of weapons which provide a bonus in games and tourneys.  I suggest these should be DM creation only.  The one's that already exist can stay of course.

Finally: There are too many variants - I would suggest simplifying things even if it means making 'swift advantage' and 'potent advantage' (etc.) functionally identical.

**Comment by Gar103** [comment]
@jrotunda Did some testing and these are actually functional, they just don't always do exactly what people expect. They're also weak and/or invisible in effect (such as adding hitroll, which you can't see, or small amounts of damage).

Justice weapons have 1.5x effect vs murderers, normal effect vs outlaws

Hall weapons give half their power outside the hall if you are guilded and own that hall. So they are 'useful' anywhere, although Meridian truncates calculations, so the most you'll ever get out of them is 1 point of damage outside the hall.

Faction weapons only work against other factions. I.e. jonas weapons work vs cess or duke factions, if you are jonas. They have half power vs unfactioned.

Colhorr weapons did actually have a calculation bug, and I've submitted a fix. Colhorr weapons actually do WORSE if you are not proficient or low proficiency.

**Comment by Gar103** [comment]
I should add, these magic mods are indeed useless, but because of balance. There is essentially no reason to ever use these mods over a proc weapon such as hold, blind, or purge. The same goes for pretty much all weapon mods, actually - hold, blind, and purge procs should probably be their own thing (in some capacity) so that the rest of the weapon mods can actually be used.

For example, I would suggest allowing Blood Inheritance to work on weapons that have faction, colhorr, or what not. That way players have a 10% chance to create a colhorr + hold proc weapon, for example. That essentially adds high level crafting, because you'd need to find an expected _ten_ powerful colhorr weapons and get a bunch of them cursed by blood inheritance failures before you produce a colhorr + hold weapon. Even then, you've only produced a _slightly_ better weapon, lol

**Comment by jrotunda** [comment]
- The damage modifier enchantment type on weapons was found to be working as intended after testing by @Gar103, with added context and design info on these weapons noted above.

- A minor design tweak was done to the Colhorr damage modifier #657 for Quality-Of-Life and greater use of and visibility for these weapons, which may influence greater interest and use of this magic weapon type.
_(good timing, pairing with the weapon/item rarity and grading system by @adrienlaws)_
