### ISSUE TITLE
NPC: Gameplay: CorGrocer Solomon isn't buying conditional items

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#628]
In *cngrocer.kod* under messages, it's indicated that Solomon in Solomon's Edibles should be open to buying some irregular items players can't normally sell around the mainland or to regular NPC's (other than Roq the Assassin who buys all the items, including eggs and junk in Meridian for medium value).

The special conditionals Solomon should purchase are the Orc Pit Boss Head, Nerudite Ore Chunks and Inky-Cap Mushrooms.

if why = MOODMOD_ACCEPT_ITEM
      {
         if IsClass(what, &OrcPitBossHead)
         {
            send(self,@SetMood,#new_mood=piMood + 10);
            return;
         }
         if IsClass(what, &NeruditeOreChunk)
         {
            send(self,@SetMood,#new_mood=piMood + 5);
            return;
         }
         if IsClass(what, &InkyCap)
         {
            send(self,@SetMood,#new_mood=piMood + 5);
            return;
         }
      }
      
      if(why = MOODMOD_SELL_ITEM)
      {
         send(self,@SetMood,#new_mood=piMood + 1);
      }
      
      return;

------------------

Currently, Solomon doesn't accept Nerudite, Inky-Cap Mushrooms or the Orc Pit Boss Head when offered.

Expectation:

Solomon should be purchasing these items (lore reason: he's from the Island and deals in rare edibles) as originally intended by his code design.

**Comment by Aesica** [comment]
Those are actually for something else--you can give him those to elevate his mood (I guess) but I don't think that's worked for a long time.  But he isn't supposed to buy them--he just takes them with a "thanks, sucker" or whatever.  if it's desired, it should be pretty easy to include those items in the list of things he buys, though.

**Comment by jrotunda** [comment]
Okay - so the issue is that he should take them and have it elevate his mood, but currently doesn't. 

Side note - changing the mood of this NPC doesn't do anything the player can notice as he's a simple buy/sell merchant.

For QOL, and an addition as you mentioned, he should not only take them on his buy list, but should pay you for them as it would be a good way to offset these items on the mainland (particularly the nerudite ore chunks). It's bad gameplay to just have an NPC take stuff from you.

**Comment by jrotunda** [comment]
Fixed. #690
