### ISSUE TITLE
Feedback: Add alternative words to the "suicide" text command to reroll your character.

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#660]
In order to reroll your character in Meridian 59, the player must enter the command, "suicide", twice, in the text-chat bar.
This word can be upsetting to both the players instructing another to type "suicide", and for the one receiving the instruction.

Although the term is effective in explaining what's happening to your character in a role-playing fashion, it's expected there be a less triggering word being used, or at least an alternative phrasing.

Suggestion to allow an alternative phrase in player.kod to perform the suicide/reroll action.

Suggestions:

**- martyr
- reroll
- self-terminate
- self-destruct
- self-delete
- delete-self
- harakiri**

Player suggestions:

**- restart
- destroy**

**Some discussion:**

_I was helping someone to reroll a character,  and they kind of had a triggering  when I was telling them to type "suicide" 
 Hadn't really considered this but maybe its time to change that command to "delete" or "reroll" ?

 — 03/18/2024 7:11 PM
it is a role playing game, you are ending your personas life...I think the command fits as to the gravity of the result of which you are doing it. There is no getting the character back even through divine intervention. delete and reroll don't really carry the same kind of weight
I can see the concern though
OP
 — 
Oh I know, its something I never even thought about, until I was telling someone to suicide because they didnt like their character. As for role Playing,  I ve never seen anyone in Meridian roleplay with any depth especially if it impacted their player needs, but I have certainly seen people get invested in attacking peoples real lives through the game. I just was thinking something less emotive_

**Comment by Aesica** [comment]
Reroll would make the most sense.
