### ISSUE TITLE
Feedback: Add 4th gender "They/Them" option for Player Display

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#661]
Meridian 59 features two genders on character startup: Male or Female

This is displayed in your player profile as "He" or "She", "Him" and "Her".

We also have a 3rd Gender, the neutral gender is "It" and is used for creatures, characters, and roleplay with DMs.

_[Note: This Gender display activates when selecting piGender = 0 or piGender = 3 in $admin for the player objects]_

It would be socially and culturally significant, relevant, and expected that the game have a They/Them option as a selection for their gender, as is done in other RPG's.

**Comment by davidklaw** [comment]
In thinking about this I wonder:
Choosing a gender as a player dictates the avatar options available to you. What do we expect to happen when someone selects a non-binary option? Would we need to allow them to choose their voice (death screams essentially)? Or maybe you choose a male or female avatar and make a new pronoun choice?

**Comment by akirmse** [comment]
I don't think this is practical to retrofit.
