### ISSUE TITLE
Client uses 100% CPU at login screen

### ISSUE THREAD

**Issue by akirmse** [Meridian59/Meridian59#679]

**Comment by Gar103** [comment]
If it helps, on my computer I experience almost exactly 30% CPU useage on the login screen and when the client is minimized. I think something is running a very high but finite number of times for some reason.

**Comment by akirmse** [comment]
I doubt that.  It is much more likely that the main thread is busy waiting.  Windows reports a single thread at 100% usage on an N core machine as 1/N overall CPU usage.

**Comment by jrotunda** [comment]
**This current client memory useage is a priority issue*;**

- Noticed and discussed by players, especially now during a busy period with our regular users staying online for longer play sessions.

- It also affects staff trying to onboard new users and support development and our unprecedented + 300% CCU and record number of retained, new, regular users and a steadily growing community. We may have one or more clients needed to be open on top of documentation, communication and search applications.

- Regular users - and new ones who did not use the previous and more 'light-weight' client - have noticed and asked about the heavy affect the client has on their computers during gameplay (let alone the above, idling on the menu)

_(@sicoderealm visuals, performance of the updated client is getting great feedback, noticed by players and staff  - better graphics, making existing content look its best, immersion, and gameplay experience greatly enhanced)_

 *_*casts mirth*...lest my computer begin a new career as a hot plate and we make this a by-design meta-feature for players enjoying extended gameplay sesssions._

**Comment by akirmse** [comment]
Fixed by https://github.com/Meridian59/Meridian59/commit/0d596af69c6026547693b66275869d3665ec93e2
