### ISSUE TITLE
Heat scrolls don't work at all

### ISSUE THREAD

**Issue by Aesica** [Meridian59/Meridian59#728]
I vaguely recall these being problematic in the past, but at the moment, trying to use a heat scroll results in failure, with the following system message sent to the player:

"There are no proper targets for heat."

To contrast, casting the heat spell in the exact same room works as expected.

**Comment by davidklaw** [comment]
The target list seems to be the culprit. When the scroll is used, the target list includes the player themselves. This blocks the cast in `GetAttackTargets` in `spell.kod`. When casting the spell, the target list goes down a different path that doesn't reach this method.

I haven't been able to determine a solution yet 😐

**Comment by Aesica** [comment]
I suspect it's going to be more than just heat, but rather, any targetless spell that does a harmful effect check upon cast.  The cleanest fix might bit a bit of work, but overall, I think it'd be worth it:

1. Adjust scrolls to not send any target information when running spell checks, etc.
2. Heat, like similar spells, would be better off castable anywhere without restriction.  Safety on + innocent target, or angeled target, would just not execute the effect on that target.

**Comment by davidklaw** [comment]
I found two possible solutions:
1. In `spelitem.kod`, bypass the `@GetTargets` call in `CastSpell` if the item in question is a scroll. I believe this might backfire if targeted spells are ever added in scroll form. Today, scrolls are only area spells.
2. In `heat.kod`, override `@GetTargets` to return a list of Battlers in the room the same way `earthqua.kod` does. This seems janky though, as there's nothing wrong with standard heat functionality.

I'm thinking it's (1) with an additional check for room enchantment just to future-proof. The scroll check makes it a little verbose, but perhaps that's helpful:

### `spelitem.kod:219`
```
% Get proper targets according to spell, assume that apply_on is our basic target.
if NOT (isClass(self,&Scroll) OR isClass(self,&RoomEnchantment))
{
      lTargets = Send(oSpell,@GetTargets,#who=what,#lTargets=[apply_on]);
}
```

Anyone have thoughts on this?
