### ISSUE TITLE
Possible inconsistencies across faction shield perks

### ISSUE THREAD

**Issue by davidklaw** [Meridian59/Meridian59#735]
The three factions' shields offer bonuses based on your faction rank (a scale of 1-10). Until #698, the first 3 levels of the Princess rank increased mana costs rather than reduced them. That PR addressed that issue by bounding the resulting value and keeping it from going negative, but also means that the first 3 levels of the Princess faction offer little to no mana cost reduction.

These are where the codebase's calculations would currently fall. Are these where we think they should be?

| piFactionRank | Mana Cost Reduction (Cess) | Added Spell Power (Duke) | Damage Reduction (Jonas) |
|---------------|------------|-----------|-----------------|
| 1             | 0          | 1         | 1               |
| 2             | 0          | 3         | 1               |
| 3             | 0          | 4         | 2               |
| 4             | 0          | 6         | 2               |
| 5             | 0          | 7         | 2               |
| 6             | 1          | 9         | 3               |
| 7             | 1          | 10        | 3               |
| 8             | 1          | 12        | 3               |
| 9             | 2          | 13        | 4               |
| 10            | 2          | 15        | 4               |

**Comment by Aesica** [comment]
Princess shield bonus is pretty terrible, even with the adjustment.  It might be worth exploring percent-based mana reduction instead of fixed value reduction, kind of like how duke membership (not the shield itself) reduces vigor cost by a percentage.  Or maybe a totally new bonus entirely.

**Comment by Gar103** [comment]
One thing I'd say is definitely don't buff the Jonas shield. It's already incredible, and the overwhelming choice (90%+). 7 armor would make it even stronger than a plate armor.

I've long felt the Princess shield bonuses were underpowered. The last thing mages need is 'even more mana,' they can take care of that themselves with high myst, cess regen itself, or crystalize mana. Honestly, the number one thing mages need more than anyone else is a reduction in post-cast timer. The 2 second post cast timer on splash and bolt spells ruins their DPS and puts long frustrating pauses in mage gameplay - cast a fireball, now do literally nothing for two full seconds until the next one. Meanwhile hybrids are snapping off a blind or purge then back to attacking with a weapon in half the time. The postcast timer is the reason basic arrows outdamage literal freaking lightning bolts.

**Comment by davidklaw** [comment]
My Jonas numbers were incorrect and have since been fixed and range from 1-4.
To be clear, these are not suggestions. These are based on the code as of #698.

**Comment by Gar103** [comment]
Is your Cess shield column missing the -1? Cess shield reduction maxes out at -2   (10 / 3 -> truncated to 3 -> -1 = 2)

**Comment by davidklaw** [comment]
It wasn't right, that's for sure.

Given `iReduction = Bound(((piFactionRank/3) - 1),0,$)` and truncation (e.g. 1.33 to 1 or 1.66 to 1), Princess' mana reduction values look like this, no? My tables above don't truncate.

| piFactionRank | Resulting Value |
|---------------|-----------------|
| 1             | 0               |
| 2             | 0               |
| 3             | 0               |
| 4             | 0               |
| 5             | 0               |
| 6             | 1               |
| 7             | 1               |
| 8             | 1               |
| 9             | 2               |
| 10            | 2               |

**Comment by Gar103** [comment]
That definitely looks right. Another thought I had was that if the mana reduction applied to Jala song tick costs too, that would be nice.
