### ISSUE TITLE
Item: Stats: NPC: Faction Soldier Quest affected by circlets; uses Max Health and not Base Max Health.

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#739]
The circlet lowers a player's HP and raises their mana. Their base max HP is not being looked at by the Faction Liege / Soldier Quest, and the player has no way of knowing this item is disallowing the quest from triggering.

I noticed this yesterday while helping a player to get the quest. The player had 85 HP, but the Circlet gave them 75HP. The Liege in question was Duke Akardius, but this also occured with Jonas (Rebel Liege) and Princess Katerrina. 

There's no indicator that the player would have to remove the circlet to trigger it.

It's expected that the quest look at the **piMax_Health and not piBase_Max_Health,** so that if the player is wearing any removeable item or has any temporary boon affecting their actual MAX HP they aren't disabled from joining a faction as a soldier.

**Comment by Gar103** [comment]
oh wow! This means you could also use Morph to bypass the hp req
