### ISSUE TITLE
Rest/Stand sometimes 'ghost fail'

### ISSUE THREAD

**Issue by Gar103** [Meridian59/Meridian59#762]
A decent percentage of the time, when you click rest, you will be told you are resting, but your vigor does not regenerate. Same thing happens when you stand... sometimes you don't actually stand, and will be unable to cast spells. It's like the client just assumes rest/stand succeeded, but the server is not receiving it, or is rejecting it for some reason.

**Comment by davidklaw** [comment]
If you are resting and quickly stand and then rest again using the UI button, the rest will fail.

https://github.com/user-attachments/assets/ec6df161-04f8-412a-bbf3-5ab6447c1327

**Comment by davidklaw** [comment]
@Meridian59 How do you feel about a solution like this, that adds a cooldown timer to any toggle buttons? The rest/stand button being the only one at the moment.

`toolbar.c`

```
void ReenableButtonAfterCooldown(Button *b)
{
   // Sleep for the cooldown period without blocking the main thread
   Sleep(BUTTON_COOLDOWN_PERIOD); // I'm thinking half a second

   // Re-enable the button after the cooldown
   EnableWindow(b->hwnd, TRUE);
}

Bool ToolbarSetButtonState(int action, void *action_data, Bool state)
{
   Button *b = ToolbarFindButtonByAction(action, action_data);
  
   if (b == NULL)
      return False;

   /* START NEW CODE */
   // Disable the button to prevent rapid toggling
   EnableWindow(b->hwnd, FALSE);

   // Start a new thread to re-enable the button after a cooldown period
   CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)ReenableButtonAfterCooldown, b, 0, NULL);
   /* END NEW CODE */

   // Set the button state (pressed or not)
   Button_SetState(b->hwnd, state);
   
   // Redraw if necessary
   if (state != b->pressed)
      InvalidateRect(b->hwnd, NULL, TRUE);
  
   b->pressed = state;

   return TRUE;
}
```

**Comment by akirmse** [comment]
Starting a thread is massive overkill.  You could just send a WM_TIMER message to the main window.  But even that sounds pretty hacky. What is the actual cause of the bug?

**Comment by davidklaw** [comment]
My understanding is that the cause is a player toggling the button quicker than the sync between client and server. The client manages it's own rest/stand state, separate from the server.
