### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by powerzist** [Meridian59/Meridian59#977]
I think codes are not utf-8 encoding, so when I deal(clone, open, compile, everything) these codes on my computer, some codes are broken. I've tried set other codepage on my computer, but it's failed. My cmd program could not recognize new codepage. Could you push all codes with utf-8 encoding?

**Comment by davidklaw** [comment]
@powerzist Could you provide details about your build environment and some screenshots showing these issues?

**Comment by powerzist** [comment]
@davidklaw Sorry for late reply.
I used Visual Studio 2022 on Windows 10, and my windows language and country settings is Korean(South).
That's why my system default code page is 949 I think.
I realized the source code's encoding is cp1252, maybe not.
Anyway, I set my system code page to 1252 by using regedit and chcp command, but it's failed.
When I tested using utf-8 encoded source code, downloading and building from Github worked well.
I tryed to change encoding of the source codes to utf-8, some codes were broken.
I attach my screenshots. (I changed my language settings to English_US)

![001](https://github.com/user-attachments/assets/746e4eae-058f-4603-83af-9866716357f3)
![002](https://github.com/user-attachments/assets/215ed12b-7670-4d28-93f9-8d6629779b44)
![003](https://github.com/user-attachments/assets/1cad0e09-5ef5-4392-bf8b-95e3815d5522)
![004](https://github.com/user-attachments/assets/9a86ba0a-2f47-4c49-9a2e-19aca5f004a1)
![005](https://github.com/user-attachments/assets/622eb9c0-86a6-4437-9034-6e9a447660c6)

**Comment by akirmse** [comment]
I believe I've fixed this file in [bc7bed8](https://github.com/Meridian59/Meridian59/commit/bc7bed88e7de94182efeb7cf7a83b16d3f01ed0e).  Please let us know if you find other problems.

**Comment by powerzist** [comment]
@akirmse Thanks for your commit and reply.
In fact, I remember there were few codes(just 1 or 2) including special characters like dialog.c file in old version. Very old version.
So, I could fix them manually.
But now, there are many codes like dialog.c file.

For example,

**roomedit/owl-6.43/include/owl/docview.rc**
-> Japanese characters such as _line 77-107_,
-> Chinese characters such as _line 140-147_

**module/char/char.rc**
-> Portuguese characters such as _line 51-_ ,
-> German characters such as _line 217-_ 

**roomedit/owl-6.43/include/owl/commview.h**
-> Special character such as _line 4_ '©' 

I've tried fix them manually, but I couldn't fix them all. Because there were so many.

Is it possible fix all of them?

**Comment by akirmse** [comment]
I tried converting clientd3d\client.rc to UTF-8, but it would no longer build.  I then tried saving it as "Unicode" (UTF-16) in Visual Studio, and it does build locally.  Can you try the git branch "utf" and see if you can build just the client (in the clientd3d directory)?

**Comment by powerzist** [comment]
@akirmse Sorry for late.
I've tried to build the codes of utf branch.
___
First, I typed 'nmake RELEASE=1' on clientd3d directory.

![001](https://github.com/user-attachments/assets/7e2dba8c-ff8f-4cfd-b38f-130678cc65b1)
___
Second, I typed 'nmake RELEASE=1' on root of Meridian59.

![002](https://github.com/user-attachments/assets/44fa0ca5-09e0-4c24-9e84-64be01ca8eb0)
___
Then I checked by typing 'nmake RELEASE=1' on clientd3d directory.

![003](https://github.com/user-attachments/assets/878a45b3-dcbf-491b-8dee-c93f4540e068)
___
And root.

![004](https://github.com/user-attachments/assets/e69f7af5-177c-4ecd-936e-27a88f317ac6)
___
Have I tested right?

**Comment by akirmse** [comment]
I would like to see the results from trying to build from the top level
directory, but your images are cut off or have all of the interesting stuff
behind the text "...skip...".  Can you send the complete output, preferably
as text instead of an image?

**Comment by powerzist** [comment]
@akirmse Sure. But text is so long. (4970 lines, 284 KB)

[nmake_log.txt](https://github.com/user-attachments/files/17728383/nmake_log.txt)

**Comment by akirmse** [comment]
FYI I got the third-party library changed, and I'll try upgrading it perhaps next week.

https://sourceforge.net/p/owlnext/bugs/591/

**Comment by powerzist** [comment]
@akirmse  No, there's no change. I did just clone utf branch, and type 'nmake RELEASE=1' on the top directory.
I did copy and paste all of output from build. I don't know why missed something.

I've tried to build codes differently one more time. I modified makefile on the top directory to remove roomedit build. Also, config.c of clientd3d was modified to connect to localhost:5959.

Building was success, but resource files was not copied properly I think. I attach build_log.txt, localclient_log.txt and one screenshot.

Thank you.

[build_log.txt](https://github.com/user-attachments/files/17743557/build_log.txt)
[localclient_log.txt](https://github.com/user-attachments/files/17743558/localclient_log.txt)
![error](https://github.com/user-attachments/assets/98a5d966-832d-4fe0-b622-01c7be9895c6)

**Comment by akirmse** [comment]
It looks like everything is working for you now.  The resource files are
not open source and thus not part of the build, as stated on the README.
Please see here:

https://github.com/Meridian59/Meridian59/issues/1017

**Comment by powerzist** [comment]
@akirmse Oh, I missed it. Thanks for your help and information.
I've built codes and copied resources successfully thanks to you.
![main](https://github.com/user-attachments/assets/d86ed72a-591f-4c76-8734-0714847c71a5)

By the way, music was not played. The localclient tried to load mid file not mp3. What should I do? I attach localclient_log.txt.
[localclient_log.txt](https://github.com/user-attachments/files/17770271/localclient_log.txt)

Thank you again.

**Comment by akirmse** [comment]
The library we use to play MP3s is not open source and we are not allowed to redistribute the library, so no, you cannot play MP3s.

**Comment by powerzist** [comment]
@akirmse Oh my god, is it real? That's too sad.
I remember localclient played mp3 in the past.
The license was changed?

**Comment by Aesica** [comment]
> @akirmse Oh my god, is it real? That's too sad. I remember localclient played mp3 in the past. The license was changed?

MP3 itself is now open source, however that doesn't mean the library M59 uses to play MP3 files is open source.

**Comment by akirmse** [comment]
The open source client has never played MP3s.

I'm going to close this, since it sounds like the encoding problem is solved.
